### ISSUE TITLE
Vector map not rendering in wrong proportion

### ISSUE THREAD

**Issue by benj5378** [maptiler/leaflet-maptilersdk#1]
first issue, lol

On the phone a map renders to wrong proportions when using a `maptilerLayer` of vector tiles when in portrait mode.

This does not happen in landscape mode. It only happens on a real phone and not on the device simulator in desktop Chrome. I obviously suspect that it is cause the renderer gets the wrong screen dimensions for rendering when in portrait mode.

Screenshot taken through remote phone debugging in Chrome (screencast of a real phone). Code available at https://github.com/benj5378/hvbmap/commit/f7841b41c536bfa6c8fe10e9a37ad224af801f40

![Screenshot from 2023-06-13 23-52-01](https://github.com/maptiler/leaflet-maptilersdk/assets/12400097/fbb91754-1ec9-4cec-94b2-c53ed3b4dbd1)

![Screenshot from 2023-06-13 23-52-27](https://github.com/maptiler/leaflet-maptilersdk/assets/12400097/cc84ff30-563f-44ce-870a-588f407812ac)

plz fix as it kinda makes it useless for use on phones :(

**Comment by jonathanlurie** [comment]
hello Benjamin, thanks for your feedback, we'll look into this asap!

**Comment by jonathanlurie** [comment]
Hey @benj5378 , I looked into it and I don't have this issue. I suspect that it is a missing `<meta>` in your project's HTML `<head>`. If you look at one of our [example](https://github.com/maptiler/leaflet-maptilersdk/blob/main/examples/basic.html#L6) you will see the following:

```html
<!DOCTYPE html>
<html>
<head>
    <title>WebGL</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      html, body, #map {
        width: 100%;
        height: 100%;
        margin: 0;
      }
    </style>
   ...
```
Where `<meta name="viewport" content="width=device-width, initial-scale=1">` guarantees that the viewport will adapt to your device at a zoom 100%.

I just tried without this line and it leads to the same issue as you posted above.
I hope it helps!
