### ISSUE TITLE
Npm package

### ISSUE THREAD

**Issue by espensgr** [maptiler/leaflet-maptilersdk#2]
I have the Maptiler sdk and Leaflet installed and using Vite as bundler, and would like to import it into the build instead of the cdn version.

Will this be an npm package, or is there a way to import it to the build?

**Comment by espensgr** [comment]
Yeah an ES module version would be great. Would be nice to be able to lazy import it into places where it is needed, instead of on every page load.

Isn't the @maptiler/sdk in ES modules to? If it is this should be too, so you can use them togehter.

**Comment by jonathanlurie** [comment]
Yes, @maptiler/sdk is exported as both an ES module and a UMD bundle. I will pass the message internally about making the leaflet plugin an ES module and we'll see how we can fit that in our current roadmap!

**Comment by gerritvanaaken** [comment]
Would love to see this. I’m trying to use the Nuxt3 Leaflet Module (https://nuxt.com/modules/nuxt3-leaflet) in combination with Vector MapTiler maps – no luck so far!

**Comment by ltoshev** [comment]
Where is the NPM module for this package?

**Comment by jonathanlurie** [comment]
Hello @ltoshev at the moment there is no NPM for this project, but it's something we are considering.

**Comment by zdila** [comment]
npm package is now available at https://www.npmjs.com/package/@maptiler/leaflet-maptilersdk
